# fly.toml app configuration file generated for msgboard on 2023-06-28T10:26:50-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "msgboard"
primary_region = "gru"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 1
  processes = ["app"]
